apiVersion: apps/v1
kind: Deployment
metadata:
  name: value-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: value-app
  template:
    metadata:
      labels:
        app: value-app
    spec:
      containers:
      - name: value-app
        image:  ivanleech/value-investing
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: value-app
spec:
  selector:
    app: value-app
  ports:
  - name: http
    port: 80
    targetPort: 5000
  type: LoadBalancer